version: '3'
services:
  api:
    image: mistermur/fwjb-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - webappnetwork
    ports:
      - "8080:8080"
    
    volumes:
    - ./:/usr/src/app
  fwjb:
    image: mistermur/fwjb-frontend
    links:
      - api
    ports:
        - "3000:3000"
    volumes:
        - /app/node_modules
        - .:/app
    stdin_open: true
    environment:
        - CHOKIDAR_USEPOLLING=true
    networks:
      - webappnetwork


networks:
  webappnetwork:
    driver: bridge